Weighted losses for multitask
allaffa/GCNN pull request #25
Opened 2021-07-14 21:16 UTC by pzhanggit

Added two types loss weights and some functions for tracking training and results visualization
Need to discuss details about better code structure

2021-07-14 22:18 UTC, streeve requested changes
These are a lot of helpful changes! I really only reviewed at the surface level - I'll take a look at the details of the loss functions/ visualization when it's cleaned up a little

2021-07-14 22:18 UTC, streeve commented on data_utils/serialized_dataset_loader.py
> +            data.y = torch.reshape(data.x[:, 2], (len(data.x), 1))
I would open a separate pull request with just this change and label it a "bug"

2021-07-14 22:18 UTC, streeve commented on examples/configuration.json
> +    "learning_rate": 1e-3,
Remove changes to this file?

2021-07-14 22:18 UTC, streeve commented on models/PNNStack.py
> +    def loss_NLL(self, pred, value):  # negative log likelihood loss
As we discussed, eventually this should be in the base class and used with any model (commenting to make sure there aren't any issues preventing that)

2021-07-14 22:18 UTC, streeve commented on utils/utils.py
> +        # true_values=test_rmse[3]; predicted_values=test_rmse[4]
Remove?

2021-07-14 22:18 UTC, streeve commented on utils/visualizer.py
> +    def create_scatter_plot_atoms_hist(
Should be able to reuse a lot of code across plotting routines

2021-07-14 22:18 UTC, streeve commented on models/PNNStack.py
> +    def loss_NLL(self, pred, value):  # negative log likelihood loss
Is there a clean way to call the different loss functions interchangeably? Also, for each added functionality, we should add a test (at least that it runs without error)

2021-07-15 01:40 UTC, allaffa approved these changes

2021-07-16 22:19 UTC, streeve commented
Closing in favor of #31

2021-07-16 22:19 UTC, closed without merging