Mpi4py
allaffa/GCNN pull request #40
Opened 2021-07-27 15:58 UTC by allaffa

2021-07-27 16:28 UTC, streeve requested changes

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +def kill_mpi_environment():
I would just call directly

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +        os.environ["MASTER_ADDR"] = master_addr
Is there no way to do this with mpi4py?

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +        """
Remove

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +        world_size = MPI.COMM_WORLD.Get_size()
Call `get_comm_size_and_rank`

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +    MPI.Init()
Probably needs to be guarded with `MPI.Is_initialized()`

2021-07-27 16:28 UTC, streeve commented on utils/utils.py
> +    MPI.Finalize()
Not sure the right way to ensure other processes continue in the session and only the last one calls

2021-07-28 15:39 UTC, jychoi-hpc approved these changes
It looks ok to me.

2021-07-30 14:24 UTC, streeve commented
Closed in favor of #42

2021-07-30 14:24 UTC, closed without merging